name: lab_8_test_417256

on:
  push:
    branches:
      - Lab8/417256

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install libs for testing
      run: |
        pip  install pytest 
    - name: Install dependencies
      run: |
        cd ./Lab_8/env_417256 && python -m pip install -r requirements.txt
    - name: Run unit tests
      run: |
        cd ./Lab_8/env_417256/main && pytest calculator_test.py

  functional_tests:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install libs for testing
      run: |
        pip  install pytest 
    - name: Install dependencies
      run: |
        cd ./Lab_8/env_417256 && python -m pip install -r requirements.txt
    - name: Run app
      run: |
          cd ./Lab_8/env_417256/main && nohup python app.py &
    - name: Sleep
      run: |
          sleep 10
    - name: Run functional tests
      run: |
        cd ./Lab_8/env_417256/main && pytest app_test.py

  deploy:
    needs: functional_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker_hub_username_417256 }}
        password: ${{ secrets.docker_hub_token_417256 }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./Lab_8/env_417256
        file: ./Lab_8/env_417256/Dockerfile
        push: true
        tags: |
          wojciechkie/lab8private:latest
          wojciechkie/lab8private:${{ github.sha }}